### ISSUE TITLE
Where can i download stored weights file of this model?. I use kaggle to train model and save weights to keras file. But when I load the model and evaluate valid dataset it doesn't work.

### ISSUE THREAD

**Issue by NguyenPhong2612** [Saptarshi-Bandopadhyay/SnapScript#1]

**Comment by Saptarshi-Bandopadhyay** [comment]
> Where can i download stored weights file of this model?

Currently I have saved the model as a whole, you can find the model in the "artifacts" folder.

> I use kaggle to train model and save weights to keras file. But when I load the model and evaluate valid dataset it doesn't work.

Are you using Keras 3 by any chance, if yes, then could you try the same with Keras 2.15.0.

**Comment by NguyenPhong2612** [comment]
Thank you, I alredy fixed this bug.

**Comment by Saptarshi-Bandopadhyay** [comment]
Awesome!! ☺️
